name: elevate_flutter_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management (MVVM / MVI)
  flutter_bloc: ^8.1.6

  # Networking
  dio: ^5.7.0

  # Dependency Injection (Bonus Points)
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Data Parsing
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Generators for DI and JSON
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true